younsl/gss

README.md
hack/charts/ghes-schedule-scanner/Chart.yaml
hack/charts/ghes-schedule-scanner/templates/cronjob.yaml
hack/charts/ghes-schedule-scanner/values.yaml
pkg/models/types.go
pkg/reporter/reporter.go
pkg/scanner/scanner.go

- helm: Support `spec.timeZone` in cronJob for helm template
- feat: Support last author info for workflow file. (Add a string type `LastCommitter` field to the model struct.)
- docs: Update summary and output example to latest
Fixes #

release: ghes-schedule-scanner v0.1.0

---

README.md

* Add external link for goroutines
* Add external link for GHES release info
Fixes #

docs: Add external links in README

---

cmd/ghes-schedule-scanner/main.go
cmd/ghes-schedule-scanner/main_test.go
pkg/scanner/scanner.go
pkg/scanner/scanner_test.go

/kind test
/kind enhancement
This PR enhances the scanner package's reliability and test coverage through:
1. Scanner Package Improvements:
- Enhanced error handling for content parsing
- Improved concurrency handling with atomic operations
- Better error messages and logging
2. Test Coverage Enhancements:
- Added comprehensive test cases for error scenarios
- Added concurrent scanning tests
- Improved mock client implementation
- Enhanced test readability with Korean descriptions
These changes improve the overall reliability and maintainability of the scanner package.
Fixes #
The test cases now include Korean descriptions for better readability, especially for Korean-speaking developers. The concurrent scanning tests verify the package's behavior under parallel execution.
N/A
- Added new …

refactor: enhance scanner package reliability and test coverage

---

deploy/charts/ghes-schedule-scanner/Chart.yaml

- Bump chart version and app version in helm chart
Fixes #

bump(helm): Set version from 0.2.0 to 0.2.1

---

README.md
cmd/ghes-schedule-scanner/main.go
cmd/ghes-schedule-scanner/main_test.go
deploy/charts/ghes-schedule-scanner/Chart.yaml
deploy/charts/ghes-schedule-scanner/templates/cronjob.yaml
pkg/scanner/scanner.go
pkg/scanner/scanner_test.go

Release 0.2.1 (previous version: 0.2.0)
Fixes #

release: ghes-schedule-scanner 0.2.1

---

.github/workflows/release-container-image.yml

/kind ci
- Automate container image CI task using actions workflow
- Support multi-platform build both amd64 and arm64
When creating a release with v0.2.2, remove the `v` prefix and upload the image as `0.2.2`. The resulting full container image URI will be `ghcr.io/younsl/gss/0.2.2`.
Fixes #

chore(ci): Create container image CI pipeline for release management

---

.github/workflows/release-container-image.yml
cmd/ghes-schedule-scanner/main.go
docs/installation.md
go.mod
go.sum
pkg/canvas/canvas.go
pkg/logger/logger.go
pkg/logger/logger_test.go
pkg/models/types.go
pkg/reporter/reporter.go
pkg/scanner/scanner.go

/kind enhancement
This PR enhances the workflow information display and adds user activity status indicators to improve visibility and usability of the schedule scanner.
Key changes:
- Add user activity status ((Active)/(Inactive)) to Last Committer field for better user tracking
- Add workflow URL as a separate line item for direct access to GitHub Actions
- Add log level configuration support for better debugging capabilities
- Improve overall readability of workflow information display
Fixes #
The workflow URL display has been implemented as a separate line item instead of an embedded link due to Slack markdown formatting limitations.
No additional documentation required as the changes are self-explanatory in the output format.
- Manual verification of Slack message formatting
- Tested …

enhancement: Add user activity status and improve workflow information display

---

deploy/charts/ghes-schedule-scanner/Chart.yaml

/kind helm
* Bump chart and app version 0.2.1 to 0.3.0
* Add new maintainer @ddukbg in Chart.yaml
Fixes #

chore(helm): Bump chart version to 0.3.0

---

docs/roadmap.md

`/kind documentation`
Updates the project roadmap to include:
- Multi-publisher system architecture details
- Messaging platform integration specifications (Slack, Discord, Teams)
- Updated status board with new prioritized tasks
- Detailed technical specifications for new features
This update is needed to address the current limitation of Canvas-only output and provide a clear path for supporting various output formats and messaging platforms.
Addresses the current limitation where scan results can only be viewed in Slack Canvas, which limits the project's adoption and usability.
The proposed features are prioritized based on:
1. **Core architecture improvements** (Multi-publisher system)
2. **Platform integrations** (Messaging platforms)
3. **Additional output formats** (Markdown, JSON) …

docs: update roadmap with multi-publisher system and messaging platform integration

---

cmd/ghes-schedule-scanner/main.go
internal/config/config.go
pkg/connectivity/checker.go
pkg/connectivity/checker_test.go

/kind enhancement
* Support network connectivity step for GHES instance in initialization step
* New component named connectivity added
This feature will be released in version 0.3.1.
Fixes #

feat: Support network connectivity in initialization

---

deploy/charts/ghes-schedule-scanner/Chart.yaml

/kind helm
- Prepare release 0.3.1
- Bump chart and app version in Chart.yaml from 0.3.0 to 0.3.1
Fixes #

bump: Chart version from 0.3.0 to 0.3.1

---

cmd/ghes-schedule-scanner/main.go
go.mod
internal/config/config.go

/kind bug
This PR resolves conflicts that occurred when merging the `feature/multi-publisher` branch with `release/0.3.1`. The conflicts were primarily in the main application structure and configuration handling.
Key changes:
- Integrate publisher functionality with config package
- Update connectivity checker implementation
- Ensure compatibility between both feature branches
This integration allows us to maintain the multi-publisher functionality while incorporating the improved configuration and connectivity features from the release branch.
The main challenge was to preserve the publisher factory pattern while adapting it to work with the new config package structure. Please pay special attention to the function signatures in `main.go` and the updated config fields in `config.go`.
No …

fix: resolve conflicts between feature/multi-publisher and release/0.3.1

---

README.md

/kind docs
- Fix inconsistent env names in README
- This PR was caused by #22
Caused by #22

docs: Fix inconsistent env names in README

---

docs/roadmap.md

* Set status from Backlog to Done by release 0.3.1
Fixes #

docs: Update status from backlog to done

---

deploy/charts/ghes-schedule-scanner/Chart.yaml
deploy/charts/ghes-schedule-scanner/templates/cronjob.yaml
deploy/charts/ghes-schedule-scanner/values.yaml

/kind helm
- Support `dnsConfig.options` to set ndots for cronJob pod
Fixes #

helm: Support dnsConfig.options value to set ndots

---

Dockerfile

/kind enhancement
Bump container images including Dockerfile:
- Bump [golang image](https://hub.docker.com/_/golang/tags) from 1.21 to 1.23
- Bump [alpine image](https://hub.docker.com/_/alpine/tags) from 3.19 to 3.21
Fixes #

bump: Dependency images

---

Dockerfile
deploy/charts/ghes-schedule-scanner/Chart.yaml
deploy/charts/ghes-schedule-scanner/templates/cronjob.yaml
deploy/charts/ghes-schedule-scanner/values.yaml

/kind release
- Release ghes-schedule-scanner 0.3.2 (Previous version: 0.3.1)
Fixes #

release: ghes-schedule-scanner 0.3.2

---

deploy/charts/ghes-schedule-scanner/templates/_helpers.tpl
deploy/charts/ghes-schedule-scanner/templates/configmap-exclude.yaml
deploy/charts/ghes-schedule-scanner/templates/cronjob.yaml
deploy/charts/ghes-schedule-scanner/values.yaml
pkg/models/types.go
pkg/publisher/slack/canvas.go
pkg/reporter/reporter.go
pkg/scanner/scanner.go

/kind feature
- Support excluding specific repositories feature
- Refactor helm chart
Fixes #

feat: Exclude repositories configuration

---

.github/workflows/release-container-image.yml

Fix `IMAGE_NAME` to organization name after transfering to containerelic organization
Fixes #

fix: set IMAGE_NAME to organization name

---

.github/workflows/release-container-image.yml

fix: username in CI workflow

---

deploy/charts/ghes-schedule-scanner/templates/_helpers.tpl
deploy/charts/ghes-schedule-scanner/templates/cronjob.yaml
deploy/charts/ghes-schedule-scanner/values.yaml

/kind helm
/kind bug
Bugfix helm rendering
Fixes #

fix(helm): Template error

---

.github/workflows/release-container-image.yml
deploy/charts/ghes-schedule-scanner/Chart.yaml
deploy/charts/ghes-schedule-scanner/templates/_helpers.tpl
deploy/charts/ghes-schedule-scanner/templates/configmap-exclude.yaml
deploy/charts/ghes-schedule-scanner/templates/cronjob.yaml
deploy/charts/ghes-schedule-scanner/values.yaml
pkg/models/types.go
pkg/publisher/slack/canvas.go
pkg/reporter/reporter.go
pkg/scanner/scanner.go

/kind release
- Release [ghes-schedule-scanner 0.4.0](https://github.com/containerelic/gss/releases/tag/v0.4.0) (previous version: 0.3.2)
> In ghes-schedule-scanner 0.4.0, support excluding specific repositories for scanning as a configuration.
Fixes #

release: ghes-schedule-scanner 0.4.0

---

pkg/publisher/slack/canvas.go
pkg/publisher/slack/canvas_test.go

/kind refactor
This PR introduces several improvements to the Slack Canvas publisher (pkg/publisher/slack):
- Refactored canvas.go: Improved code structure and introduced robust retry logic with exponential backoff for updateCanvas to handle transient network errors and Slack API rate limits (429, 5xx).
- Enhanced Unit Tests (canvas_test.go): Added comprehensive unit tests covering the refactored code, including various scenarios for the retry mechanism, API errors, HTTP errors, and configuration issues.
- Improved Test Stability: Resolved multiple test failures related to mock handlers and context propagation within the test environment.
- Achieved High Test Coverage: Reached 83.6% test coverage for the pkg/publisher/slack package.
These changes enhance the reliability of the Slack …

refactor: Slack canvas publisher and enhance tests

---

README.md
docs/acknowledgements.md

/kind documentation
* Add acknowledgements page
* Update main README in root directory
Fixes #

docs: Add acknowledgements page

---

.github/workflows/codeql.yml

/kind cicd
* Automate application security scanning using CodeQL advanced
Fixes #

security(ci): Add golang CodeQL advanced to enhance security

---

pkg/publisher/slack/canvas.go

/kind bug
- fix(canvas): Broken repo URL due to `/.github/workflows/` duplication
This PR was caused by https://github.com/containerelic/gss/pull/36
Fixes #

fix(canvas): Broken repo URL

---

.github/workflows/release-container-image.yml
Dockerfile
deploy/charts/ghes-schedule-scanner/Chart.yaml
internal/version/version.go
pkg/publisher/slack/canvas.go
pkg/reporter/reporter.go

/kind chore
- Add version component to print version in output log and table
Fixes #

chore: Add version component

---

.github/workflows/release-container-image.yml

/kind chore
- Fix CI workflow to release container image 0.4.1
Fixes #

fix: release workflow

---

.github/workflows/release-helm-chart.yml

/kind ci
- Make release helm pipeline
Fixes #

chore(ci): Update release helm chart

---

deploy/charts/ghes-schedule-scanner/Chart.yaml
deploy/charts/ghes-schedule-scanner/README.md

/kind helm
- Bump minor version chart
- Add deprecated field and set false
Fixes #

docs(helm): Bump chart minor version

---

Dockerfile
README.md
go.mod

bump: Pin go 1.25.0
